---
- name: Install Packages
  dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - '{{ packages }}'
  become: yes

- name: Change file ownership, group and permissions vagrant for Apache
  file:
    path: '{{ http_conf }}'
    owner: vagrant
    group: vagrant
  become: yes