#
# LICENSE UPL 1.0
#
# Copyright (c) 1982-2020 Oracle and/or its affiliates. All rights reserved.
#
# Since: January, 2020
# Author: gerald.venzl@oracle.com
# Description: Creates an Oracle Linux virtual machine.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Box metadata location and box name
BOX_URL = "https://oracle.github.io/vagrant-projects/boxes"
BOX_NAME = "oraclelinux/8"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_NAME
  config.vm.box_url = "#{BOX_URL}/#{BOX_NAME}.json"

  # VM apache
  config.vm.define "apache" do |apache|

    # HOSTNAME
    apache.vm.hostname = "ol-apache"

    # NETWORK
    apache.vm.network "public_network" ,ip: "192.168.0.135" ,mode: "bridge" , bridge: "ens32"
    apache.vm.network "forwarded_port", guest: 80, host: 8080, adapter: 1 , guest_ip: "192.168.0.135" ,host_ip: "192.168.0.33"

    # MOUNTS
    apache.vm.synced_folder ".", "/vagrant", disabled: true
    apache.vm.synced_folder "./security", "/home/vagrant/security"

    # PROVIDER
    apache.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name = "ol-apache"
      vb.memory = 1024
      vb.cpus = 1
    end

    # PROVISION
    # SSH,FIREWALLD AND SELINUX
    apache.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/security/id_rsa.pub >> .ssh/authorized_keys
      chmod 600 /home/vagrant/security/id_rsa
      chown vagrant:vagrant /home/vagrant/security/id_rsa
      sudo systemctl stop firewalld
      sudo systemctl disable firewalld
      sudo setenforce Permissive
      SHELL

    # INSTALL UPDATES AND TOOLS
    apache.vm.provision "shell",inline: <<-SHELL
      # sudo yum update -y
      dnf install python3 -y
      SHELL

    apache.vm.provision "ansible" do |ansible|
      ansible.limit = "all"
      ansible.inventory_path = "provisioning/hosts"
      ansible.playbook = "provisioning/site.yml"

    end

  end

end